#!/usr/bin/perl
use v5.16;

#ex1
#my @skipper = qw(blue_shirt hat jacket preserver sunscreen);
#my @professor = qw(sunscreen water_bottle slide_rule batteries radio);
#my @gilligan = qw(red_shirt hat lucky_socks water_bottle);
#
#my %all = (
#	Gilligan => \@gilligan,
#	Skipper => \@skipper,
#	Professor => \@professor,
#);
#
#check_items_for_all(\%all);
#
#sub check_items_for_all {
#	my $hash_ref = shift;
#	foreach my $who (keys %$hash_ref) {
##		check_required_items($who, %$hash_ref{$who});
#		check_required_items($who, $hash_ref->{$who});
#	}
#
#}
#
#sub check_required_items {
#	my $who = shift;
#	my $items = shift;
#	my %whose_items = map {$_, 1} @$items;
#	my @required = qw(preserver sunscreen water_bottle jacket);
#	my @missing = ();
#	
#	for my $item (@required) {
#		unless ($whose_items{$item}) {
#			print "$who is missing $item.\n";
#			push @missing, $item;
#		}
#	}
#	
#	if (@missing) {
#		print "Adding @missing to @$items for $who.\n";
#		push @$items, @missing;
#	}
#}


#ex2
my %gilligan_info = (
	name 	=>	'Gilligan',
	hat		=> 	'White',
	shirt	=>	'Red',
	position=>	'First Mate',
);
my %skipper_info = (
	name 	=>	'Skipper',
	hat		=>	'Black',
	shirt	=>	'Blue',
	position=>	'Captain',
);
my %mr_howell_info = (
	name	=> 	'Mr. Howell',
	hat		=>	'Blue',
	shirt	=> 	'Red',
	position=>	'Shanghai',
);
my %mrs_howell_info = (
	name	=>	'Mrs. Howell',
	hat		=>	'Yellow',
	shirt	=>	'Greed',
	position=>	'Shanghai',
);

my @crew = (\%gilligan_info, \%skipper_info,
	\%mr_howell_info, \%mrs_howell_info);

#my $format = "%-15s %-7s %-7s %-15s\n";
#printf $format, qw(Name Shirt Hat Position);
foreach my $crewmember (@crew) {
	$crewmember->{'position'} = 'The Island Country Clus'
		if $crewmember->{'name'} =~ /howell/i;
	print "$crewmember->{'name'} at $crewmember->{'position'}\n";
#	printf $format,
#		$crewmember->{'name'},
#		$crewmember->{'shirt'},
#		$crewmember->{'hat'},
#		$crewmember->{'position'};
}

